server:
  port: 9082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: itf
  application:
    name: "loans"

build:
  info: 0.0.1-SNAPSHOT

loans:
  message: "Welcome to SKD Bank loans service, environment - local "
  contactDetails:
    name: "Sumeet Dwivedi - Developer"
    email: "sumeet@skdbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345