
spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:9083/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
  data: #configuration for RedisRateLimiter
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway"
    description: "SKD Bank APIGateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      skd:
        apigateway: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

