server:
  port: 9083

spring:
  profiles:
    active: native
  application:
    name: "configserver"
  cloud:
    config:
      server:
       native:
#         search-locations: "classpath:/config"
         search-locations: "file:///C://Users//er_sk//Downloads//config"