server:
  port: 9083

spring:
  profiles:
    active: git
#    active: native
  application:
    name: "configserver"
  cloud:
    config:
      server:

#        native:
#         search-locations: "classpath:/config"
#         search-locations: "file:///C://Users//er_sk//Downloads//config"
        git:
          uri: "https://github.com/motivated-coder/config"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true



encrypt:
  key: "skd"
