services:

  rabbitmq:
    image: "rabbitmq:3.12-management"
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "111190/configserver:s1"
    container_name: "configserver_ms"
    ports:
      - 9083:9083
    healthcheck:
      test: "curl --fail --silent localhost:9083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "111190/accounts:s1"
    container_name: "accounts_ms"
    ports:
      - 9080:9080
    environment:
      SPRING_APPLICATION_NAME : "accounts"
    extends:
      file: common-config.yml
      service: microservice-service-config

  cards:
    image: "111190/cards:s1"
    container_name: "cards_ms"
    ports:
      - 9081:9081
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-service-config

  loans:
    image: "111190/loans:s1"
    container_name: "loans_ms"
    ports:
      - 9082:9082
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-service-config

networks:
  skd:
    driver: "bridge"
